### ISSUE TITLE
onError is not triggered when page is not found and file resolution is dynamic

### ISSUE THREAD

**Issue by HKGx** [elysiajs/elysia-static#10]
https://github.com/elysiajs/elysia-static/blob/57cbb4f91f42c168b5810567bf081f7bfb1ec4e9/src/index.ts#L141-L146

**Comment by SaltyAom** [comment]
Fixed with 0.7.1 https://github.com/elysiajs/elysia-static/commit/403223119bdc52910c75044b7cf5ebf4bda01699

Let me know if the problem still persists
