### ISSUE TITLE
Latest version doesn't work

### ISSUE THREAD

**Issue by grctest** [elysiajs/elysia-static#11]
Using the latest 0.7 elysia + 0.6 works, but using static 0.7 with `.use(staticPlugin({ prefix: '/' }))` causes the following warning in vscode:

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'Promise<Elysia<"", { store: {}; request: {}; schema: {}; error: {}; meta: { schema: {}; defs: {}; exposed: {}; }; }>>' is not assignable to parameter of type 'Promise<{ default: (elysia: Elysia<any, any>) => Elysia<any, ElysiaInstance>; }>'.
      Property 'default' is missing in type 'Elysia<"", { store: {}; request: {}; schema: {}; error: {}; meta: { schema: {}; defs: {}; exposed: {}; }; }>' but required in type '{ default: (elysia: Elysia<any, any>) => Elysia<any, ElysiaInstance>; }'.ts(2769)
index.d.ts(198, 9): 'default' is declared here.
index.d.ts(197, 5): The last overload is declared here.
```

In the terminal it complains about config, but using `.use(staticPlugin())` results in the same error.

**Comment by calumk** [comment]
Latest version also not working for me 

```
TypeError: undefined is not an object (evaluating 'X.config')
      at Y (/Volumes/Programming/2023_3/app/node_modules/elysia/dist/bun/index.js:272:25995)
```

**Comment by Ricki-BumbleDev** [comment]
I had the same problem. I fixed it by making sure I had the latest version of this package and elysia. If you use compatible versions in your `package.json` (marked with the `^`) it's best to delete `node_modules` and the lock file and then install again, to make sure you are actually installing the latest versions.

**Comment by TomieAi** [comment]
same not working.. at all it says not found only even tho i followed the structure

```
 - src
  | - index.ts
| - public
  | - takodachi.png
  | - nested
    | - takodachi.png
```

**Comment by bogeychan** [comment]
Thanks for reporting this finding!

Please try the latest versions and clean re-install like as suggested by @Ricki-BumbleDev.

Fell free to reopen this issue if it persists.
