### ISSUE TITLE
Navigate to folder `public/` throws `File must be regular or FIFO` error

### ISSUE THREAD

**Issue by bogeychan** [elysiajs/elysia-static#17]
### Code to reproduce

```ts
import { Elysia } from 'elysia';
import { staticPlugin } from '@elysiajs/static';

new Elysia().use(staticPlugin()).listen(8080);
```

### Folder structure

- `public`
  - `nested`

### Navigate to

- `http://localhost:8080/public/`
- `http://localhost:8080/public/nested/`

### Error

```bash
EINVAL: File must be regular or FIFO
   path: "public/"
 syscall: "sendfile"
   errno: -22

GET - http://localhost:8080/public/ failed
```

### Environment

- elysia@0.7.21
- bun@1.0.9

**Comment by bogeychan** [comment]
as a workaround one can add ignore patterns for each folder and subfolder like:

Folder structure:

- public
  - nested

```ts
staticPlugin({
  ignorePatterns: [/public\/?/, /public\/nested\/?/]
});
```

make sure to include the default patterns too: https://github.com/elysiajs/elysia-static/blob/403223119bdc52910c75044b7cf5ebf4bda01699/src/index.ts#L29

**Comment by tnfAngel** [comment]
Same for me
