### ISSUE TITLE
prefix '/' conflicts with get('*')

### ISSUE THREAD

**Issue by Gn3po4g** [elysiajs/elysia-static#27]
```typescript
new Elysia()
.use(staticPlugin({prefix: '/' }))
.get('*', "hello")
.listen(3000)
```
When build elysia as above, all requrest goes to `get('*')`. So could set `get()` as a fallback? That is, the request first goes to match static resources, and then matches the get route if static file is not found.

**Comment by Gn3po4g** [comment]
maybe like this
```typescript
const loadStatic = (root: string) => async (app: Elysia) => {
  readdirSync(root, { recursive: true, withFileTypes: true })
    .filter(file => file.isFile())
    .forEach(file => app.get(file.name, Bun.file(`${root}/${file.name}`)))
  return app
}
```

**Comment by bogeychan** [comment]
Thanks for reporting this finding!

Can't reproduce it on my end. Can you give it a try with the latest versions?

**Comment by Gn3po4g** [comment]
Yes. It works when I set the prefix to any path, like `/p`.
I can get `test.txt` from `/p/test.txt`. But if i set prefix to `/`, I get `hello` from `/test,txt`

elysia 1.1.26
elysia-static 1.1.1

**Comment by bogeychan** [comment]
You've to use the `alwaysStatic` option:

```ts
import { Elysia } from "elysia";
import { staticPlugin } from "@elysiajs/static";

new Elysia()
  .use(staticPlugin({ prefix: "/", alwaysStatic: true }))
  .get("*", "hello")
  .listen(3000);
```

Otherwise, the routes are resolved lazily when they are called; your wildcard route basically overrides them.

**Comment by Gn3po4g** [comment]
it works :)
