### ISSUE TITLE
Support assets in a sibling directory

### ISSUE THREAD

**Issue by JeanMeche** [elysiajs/elysia-static#42]
I was trying to use elysia in combination of Angular SSR. 

Here is basically my server config. 
```
import { AngularAppEngine, createRequestHandler } from '@angular/ssr';
import { isMainModule } from '@angular/ssr/node';
import { Elysia } from 'elysia';
import { staticPlugin } from '@elysiajs/static';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export function app() {
  const server = new Elysia();
  const angularAppEngine = new AngularAppEngine();

  const serverDistFolder = dirname(fileURLToPath(import.meta.url));
  const browserDistFolder = resolve(serverDistFolder, '../browser');

  server.use(staticPlugin({
    prefix: '',
    assets: browserDistFolder,
    alwaysStatic: true,
  }));

  server.get('/*', async (c) => {
    const res = await angularAppEngine.handle(c.request, { server: 'elysia' });
    return res || undefined;
  });

  console.warn('Elysia server started');

  return server;
}

const server = app();
if (isMainModule(import.meta.url)) {
  const port = process.env['PORT'] || 4000;

  server.listen(port, () => {
    console.log(`Elysia server listening on http://localhost:${port}`);
  });
}

export const reqHandler = createRequestHandler(server.fetch);
```

When building an SSR app, Angular generates 2 bundles, a server and a static csr one: 

* `./server`
* `./browser`

The forementioned server config is located in the `server` directory and as you can see, we need to pull the static asset from the `../browser` directory, a sibling of the parent directory. 

And it seems like that `elysia-static` doesn't support that.

**Comment by JeanMeche** [comment]
This was fixed by bumping to 1.2 ! 🚀

**Comment by JeanMeche** [comment]
@draylegend I couldn't reproduce the issue. Could you try to delete `.angular` and retry ?

**Comment by draylegend** [comment]
@JeanMeche I'm using WSL2 with debian 12 and bun 1.1.42. I deleted `.angular` and `.nx` folders, but still builds with the same error

**Comment by JeanMeche** [comment]
It might be worth reporting to the angular/cli repo directly.

**Comment by draylegend** [comment]
I'll report it, thank you!
